name: cat_adoption
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  get: ^4.1.1
  lottie: ^1.0.1
  animated_text_kit: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Circe
      fonts:
        - asset: assets/fonts/CirceRounded-Regular.otf
    - family: Vialog
      fonts:
        - asset: assets/fonts/vialog-lt-regular.ttf
